name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    # Removed cache step due to possible vendor inconsistencies

    - name: Clean and install Composer dependencies
      run: |
        rm -rf vendor
        composer clear-cache
        composer install --prefer-dist --no-progress --no-scripts

    - name: Dump autoload
      run: composer dump-autoload -o

    - name: Run test suite
      run: composer run test
